# [colors.bright]
# black = "#555753"
# blue = "#729fcf"
# cyan = "#34e2e2"
# green = "#8ae234"
# magenta = "#ad7fa8"
# red = "#ef2929"
# white = "#eeeeec"
# yellow = "#fce94f"
# 
# [colors.cursor]
# cursor = "#ffffff"
# text = "#000000"
# 
# [colors.normal]
# black = "#000000"
# blue = "#3465a4"
# cyan = "#06989a"
# green = "#4e9a06"
# magenta = "#75507b"
# red = "#cc0000"
# white = "#d3d7cf"
# yellow = "#c4a000"
# 
# [colors.primary]
# background = "#000000"
# foreground = "#ffffff"
# 
# [debug]
# highlight_damage = false
# print_events = false
# 
# [font]
# size = 7
# 
# [font.bold]
# family = "SauceCodePro Nerd Font Mono"
# style = "Bold"
# 
# [font.bold_italic]
# family = "SauceCodePro Nerd Font Mono"
# style = "Bold Italic"
# 
# [font.italic]
# family = "SauceCodePro Nerd Font Mono"
# style = "Italic"
# 
# [font.normal]
# family = "SauceCodePro Nerd Font Mono"
# style = "Regular"
# 
# [[keyboard.bindings]]
# action = "Paste"
# key = "V"
# mode = "~Vi"
# mods = "Control|Shift"
# 
# [[keyboard.bindings]]
# action = "Copy"
# key = "C"
# mods = "Control|Shift"
# 
# [[keyboard.bindings]]
# action = "SearchForward"
# key = "F"
# mode = "~Search"
# mods = "Control|Shift"
# 
# [[keyboard.bindings]]
# action = "SearchBackward"
# key = "B"
# mode = "~Search"
# mods = "Control|Shift"
# 
# [[keyboard.bindings]]
# action = "IncreaseFontSize"
# key = "Plus"
# mods = "Control"
# 
# [[keyboard.bindings]]
# action = "DecreaseFontSize"
# key = "Minus"
# mods = "Control"
# 
# [[keyboard.bindings]]
# action = "SpawnNewInstance"
# key = "Return"
# mods = "Control|Shift"

[window]
dynamic_title = true
opacity = 0.85
title = "Alacritty"

# [window.padding]
# x = 4
# y = 4
